; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:lilygo-t-display-s3]
; pioarduino build of espressif32 (Arduino core 3.1.1)
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    h2zero/NimBLE-Arduino@^2.3.0
    sui77/rc-switch@^2.6.4
